// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-git/go-git/v5/plumbing/object (interfaces: CommitIter)

// Package core is a generated GoMock package.
package core

import (
	reflect "reflect"

	object "github.com/go-git/go-git/v5/plumbing/object"
	gomock "github.com/golang/mock/gomock"
)

// MockCommitIter is a mock of CommitIter interface.
type MockCommitIter struct {
	ctrl     *gomock.Controller
	recorder *MockCommitIterMockRecorder
}

// MockCommitIterMockRecorder is the mock recorder for MockCommitIter.
type MockCommitIterMockRecorder struct {
	mock *MockCommitIter
}

// NewMockCommitIter creates a new mock instance.
func NewMockCommitIter(ctrl *gomock.Controller) *MockCommitIter {
	mock := &MockCommitIter{ctrl: ctrl}
	mock.recorder = &MockCommitIterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommitIter) EXPECT() *MockCommitIterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCommitIter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCommitIterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCommitIter)(nil).Close))
}

// ForEach mocks base method.
func (m *MockCommitIter) ForEach(arg0 func(*object.Commit) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForEach", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForEach indicates an expected call of ForEach.
func (mr *MockCommitIterMockRecorder) ForEach(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEach", reflect.TypeOf((*MockCommitIter)(nil).ForEach), arg0)
}

// Next mocks base method.
func (m *MockCommitIter) Next() (*object.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(*object.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockCommitIterMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockCommitIter)(nil).Next))
}
